apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: romenzonez/ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: development-build-stage       
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: romenzonez/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
        target: development-build-stage
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
          - src: '**/*.tsx'
            dest: .
    - image: romenzonez/ticketing-tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
        target: development-build-stage
      sync:
        manual:
          - src: '**/*.go'
            dest: .
    - image: romenzonez/ticketing-orders
      context: orders
      docker:
        dockerfile: Dockerfile
        target: development-build-stage
      sync:
        manual:
          - src: '**/*.go'
            dest: .
    - image: romenzonez/ticketing-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
        target: development-build-stage
      sync:
        manual:
          - src: '**/*.go' 
            dest: .
    - image: romenzonez/ticketing-payments
      context: payments
      docker:
        dockerfile: Dockerfile
        target: development-build-stage
      sync:
        manual:
          - src: '**/*.go' 
            dest: .