name: Golang fiber boilerplate CI

on:
  push:
    branches:
      - main

jobs:
  build:

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_DATABASE: go_api_boilerplate_test
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      APP_NAME: "Go API Boilerplate"
      APP_PORT: 3000
      APP_PREFORK: false
      APP_TIMEOUT: 10
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: go_api_boilerplate_test
      POOL_IDLE: 5
      POOL_MAX: 100
      POOL_LIFETIME: 3000
      LOG_LEVEL: 6
      JWT_SECRET_KEY: secretkey

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependencies
        run: go mod tidy
      - name: Run unit tests
        run: make test.unit
      - name: Run integration tests
        run: make test.integration