apiVersion: v1
kind: PersistentVolume
metadata:
  name: orders-mysql-pv
  labels:
    type: local # Sets the type of volume
    app: orders-mysql
spec:
  storageClassName: orders-mysql-class # Sets the storage class to be used for PVC
  capacity:
    storage: 1Gi # Sets the volume size
  accessModes:
    - ReadWriteOnce # Sets read and write access
  hostPath:
    path: "/var/lib/orders-mysql" # Sets the path on the host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-mysql-pvc
  labels:
    app: orders-mysql
spec:
  storageClassName: orders-mysql-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: orders-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mysql
  template:
    metadata:
      labels:
        app: orders-mysql
    spec:
      containers:
        - name: orders-mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: '1'
            - name: MYSQL_DATABASE
              value: 'orders'
            - name: MYSQL_USER
              value: 'testuser'
            - name: MYSQL_PASSWORD
              value: 'testpassword'
          volumeMounts:
            - name: orders-mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: orders-mysql-storage
          persistentVolumeClaim:
            claimName: orders-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: orders-mysql-srv
spec:
  selector:
    app: orders-mysql
  ports:
    - name: orders-mysql
      protocol: TCP
      port: 3306
      targetPort: 3306