apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-client
  template:
    metadata:
      labels:
        app: ticketing-client
    spec:
      containers:
        - name: ticketing-client
          image: romenzonez/ticketing-client
          env:
            - name: API_GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: api-gateway-url 
                  key: API_GATEWAY_URL
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-client-srv
spec:
  selector:
    app: ticketing-client
  ports:
    - name: ticketing-client
      protocol: TCP
      port: 3000
      targetPort: 3000