apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-payments
  template:
    metadata:
      labels:
        app: ticketing-payments
    spec:
      containers:
        - name: ticketing-payments
          image: romenzonez/ticketing-payments
          env:
            - name: APP_PORT
              value: '3000'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: JWT_SECRET_KEY
              value: 'asdfasdf'
            - name: DB_USER
              value: 'root'
            - name: DB_PASSWORD
              value: ''
            - name: DB_HOST
              value: 'payments-mysql-srv'
            - name: DB_PORT
              value: '3306'
            - name: DB_NAME
              value: 'payments'
            - name: LOG_LEVEL
              value: '2'
            - name: STRIPE_KEY
              value: 'sk_test_51NuxwkEPFj7I6FUPMJqh9CQ6Woc8Rm5bSvYpMT6zCBISCVz3XLLQg9BFtUvPh5qqm6kosy5FaWo89JqFBaAsz31T00KI1CX9ke'
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-payments-srv
spec:
  selector:
    app: ticketing-payments
  ports:
    - name: ticketing-payments
      protocol: TCP
      port: 3000
      targetPort: 3000