basePath: /api
definitions:
  model.CreateOrderRequest:
    properties:
      ticket_id:
        type: integer
      user_id:
        type: string
    required:
    - ticket_id
    - user_id
    type: object
  model.OrderResponse:
    properties:
      created_at:
        type: integer
      expires_at:
        type: integer
      id:
        type: integer
      status:
        type: string
      ticket:
        $ref: '#/definitions/model.TicketResponse'
      updated_at:
        type: integer
      user_id:
        type: string
    type: object
  model.TicketResponse:
    properties:
      id:
        type: integer
      price:
        type: integer
      title:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: Orders Service HTTP API Docs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Orders Service
  version: "1.0"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: Fetches all order data.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.OrderResponse'
            type: array
      security:
      - Session: []
      summary: Get All Orders
      tags:
      - Orders
    post:
      consumes:
      - application/json
      description: Create a new order.
      parameters:
      - description: Order Create Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.OrderResponse'
      security:
      - Session: []
      summary: Create Order
      tags:
      - Orders
  /orders/{id}:
    delete:
      description: a order by id.
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      security:
      - Session: []
      summary: Cancels A Order
      tags:
      - Orders
    get:
      description: Fetches a order by id.
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OrderResponse'
      security:
      - Session: []
      summary: Get A Order
      tags:
      - Orders
securityDefinitions:
  Session:
    in: header
    name: Cookie
    type: apiKey
swagger: "2.0"
